// London landmarks for the map's history layer. Static, curated, sourced —
// rendered as a brass symbol layer in PubMapCanvas, tapped for a history card.

import { haversineKm } from "@/lib/haversine";
export { nearestStoryPubs } from "@/lib/landmarkVenueProximity";
export type { NearbyStoryPub } from "@/lib/landmarkVenueProximity";
import attributionTable from "@/public/data/landmark_image_attribution.json";

export type Landmark = {
  id: string;
  name: string;
  /** [lng, lat] */
  coordinates: [number, number];
  /** 2-3 short sourced sentences. */
  history: string;
  source: { label: string; url: string };
  /**
   * Marker pictogram key (lib/mapIcons ns "lm"). The canvas draws a recognisable
   * chunky silhouette for this landmark instead of a generic glyph. Kept a bare
   * string so this data module stays decoupled from the icon-drawing library.
   */
  icon: string;
  /**
   * A real, freely-licensed photo shown at the top of the landmark history card.
   * Wikimedia Commons Special:FilePath URLs — a stable redirect that always
   * resolves to the current file, so the link never rots to a dead thumbnail.
   *
   * `credit` stays as the platform name ("Wikimedia Commons") for the card's
   * "via" link, but CC-BY / CC-BY-SA require the author + licence + a link back
   * to the file page too. Those come from the committed, observed-at attribution
   * table (public/data/landmark_image_attribution.json, regenerated by
   * scripts/enrich_landmark_attribution.mjs) and are merged in by `commons()`
   * below, so nothing is fetched at render time. `licenseUrl` is empty for a
   * public-domain file (no licence to link).
   */
  image?: LandmarkImage;
};

export type LandmarkImage = {
  url: string;
  credit: string;
  author?: string;
  licenseShortName?: string;
  licenseUrl?: string;
  sourcePageUrl?: string;
};

type AttributionRow = {
  author?: string;
  licenseShortName?: string;
  licenseUrl?: string;
  sourcePageUrl?: string;
};

const attribution = attributionTable.files as Record<string, AttributionRow>;

// Every landmark photo is a Wikimedia Commons image reached through the
// Special:FilePath redirect (…/Special:FilePath/<File>?width=800). We keep them
// here rather than downloading into the bundle so the app stays lean. The
// compliant attribution (author + licence + file-page link) is merged from the
// committed Commons attribution table, keyed by the exact encoded filename.
const commons = (file: string): LandmarkImage => {
  const attr = attribution[file];
  return {
    url: `https://commons.wikimedia.org/wiki/Special:FilePath/${file}?width=800`,
    credit: "Wikimedia Commons",
    author: attr?.author || undefined,
    licenseShortName: attr?.licenseShortName || undefined,
    licenseUrl: attr?.licenseUrl || undefined,
    sourcePageUrl: attr?.sourcePageUrl || undefined,
  };
};

export const landmarks: Landmark[] = [
  {
    id: "big-ben",
    name: "Big Ben",
    coordinates: [-0.1246, 51.5007],
    icon: "clock-tower",
    image: commons("Elizabeth_Tower%2C_June_2022.jpg"),
    history:
      "Big Ben is the nickname of the Great Bell inside the clock tower of the Palace of Westminster, first rung in 1859. The tower itself was renamed the Elizabeth Tower in 2012 to mark Queen Elizabeth II's Diamond Jubilee.",
    source: {
      label: "UK Parliament",
      url: "https://www.parliament.uk/bigben",
    },
  },
  {
    id: "westminster-abbey",
    name: "Westminster Abbey",
    coordinates: [-0.1281, 51.4994],
    icon: "civic",
    image: commons("Westminster_Abbey%2C_Westminster.jpg"),
    history:
      "Westminster Abbey was consecrated in 1065 under Edward the Confessor and rebuilt in the Gothic style begun by Henry III in 1245. Since the coronation of William the Conqueror in 1066 it has been the coronation church of England's, then Britain's, monarchs.",
    source: {
      label: "Westminster Abbey",
      url: "https://www.westminster-abbey.org/history/history-of-westminster-abbey",
    },
  },
  {
    id: "nelsons-column",
    name: "Nelson's Column",
    coordinates: [-0.1281, 51.5079],
    icon: "column",
    image: commons("Nelson%27s_Column%2C_Trafalgar_Square%2C_London.JPG"),
    history:
      "Nelson's Column has stood at the centre of Trafalgar Square since 1843, commemorating Admiral Horatio Nelson, who was killed at the Battle of Trafalgar in 1805. Designed by William Railton, the granite Corinthian column rises about 52 metres and is topped by Edward Hodges Baily's statue of Nelson.",
    source: {
      label: "Britannica",
      url: "https://www.britannica.com/place/Nelsons-Column",
    },
  },
  {
    id: "british-museum",
    name: "British Museum",
    coordinates: [-0.127, 51.5194],
    icon: "civic",
    image: commons("British_Museum_%28aerial%29.jpg"),
    history:
      "The British Museum was established by Act of Parliament in 1753 as the first national public museum in the world. Its landmark Greek Revival building on Great Russell Street, designed by Sir Robert Smirke, was built between 1823 and 1852.",
    source: {
      label: "British Museum",
      url: "https://www.britishmuseum.org/about-us/british-museum-story/history",
    },
  },
  {
    id: "shakespeares-globe",
    name: "Shakespeare's Globe",
    coordinates: [-0.0972, 51.5081],
    icon: "civic",
    image: commons("Restaurante_The_Swan%2C_Londres%2C_Inglaterra%2C_2014-08-11%2C_DD_113.jpg"),
    history:
      "This Bankside theatre is a reconstruction of the Elizabethan Globe, first built in 1599 for the company that staged Shakespeare's plays. Championed by the actor Sam Wanamaker, the modern Globe opened close to the original site in 1997.",
    source: {
      label: "Shakespeare's Globe",
      url: "https://www.shakespearesglobe.com/discover/about-us/globe-theatre/",
    },
  },
  {
    id: "barbican",
    name: "Barbican Centre",
    coordinates: [-0.0937, 51.52],
    icon: "civic",
    image: commons("Barbican_Lakeside_on_a_summer_evening.jpg"),
    history:
      "The Barbican is a landmark of post-war Brutalist architecture, designed by Chamberlin, Powell and Bon on land in the City of London flattened by wartime bombing. Its arts centre opened in 1982, and the surrounding estate was Grade II listed in 2001.",
    source: {
      label: "City of London",
      url: "https://www.cityoflondon.gov.uk/services/barbican-estate/barbican-estate-history",
    },
  },
  {
    id: "camden-lock",
    name: "Camden Lock",
    coordinates: [-0.1466, 51.5416],
    icon: "canal",
    image: commons("Camden_Lock_London.jpg"),
    history:
      "Camden Lock sits beside the Hampstead Road Locks on the Regent's Canal, opened in 1820 to link London's docks to the national canal network. As canal trade faded, a crafts market started here in 1974 and grew into one of London's best-known markets.",
    source: {
      label: "Wikipedia",
      url: "https://en.wikipedia.org/wiki/Camden_Lock",
    },
  },
  {
    id: "royal-albert-hall",
    name: "Royal Albert Hall",
    coordinates: [-0.1774, 51.501],
    icon: "dome",
    image: commons("Royal_Albert_Hall%2C_London_-_Nov_2012.jpg"),
    history:
      "The Royal Albert Hall was opened by Queen Victoria in 1871 as part of a memorial to her husband Prince Albert, whose vision it fulfilled in South Kensington. The Grade I listed concert hall has hosted the BBC Proms every summer since 1941.",
    source: {
      label: "Royal Albert Hall",
      url: "https://www.royalalberthall.com/about-the-hall/our-history/",
    },
  },
  {
    id: "natural-history-museum",
    name: "Natural History Museum",
    coordinates: [-0.1763, 51.4967],
    icon: "civic",
    image: commons("Natural_History_Museum_London_Jan_2006.jpg"),
    history:
      "The Natural History Museum on Cromwell Road opened in 1881 to house the national natural history collections. Alfred Waterhouse's cathedral-like building is clad in terracotta moulded with animals and plants, a Romanesque landmark of South Kensington.",
    source: {
      label: "Natural History Museum",
      url: "https://www.nhm.ac.uk/about-us/history-and-architecture.html",
    },
  },
  {
    id: "battersea-power-station",
    name: "Battersea Power Station",
    coordinates: [-0.1447, 51.4816],
    icon: "chimneys",
    image: commons("Battersea_Power_Station_from_the_river.jpg"),
    history:
      "Battersea Power Station's four white chimneys, on a building by Sir Giles Gilbert Scott, rose beside the Thames between 1929 and 1955. It generated electricity until 1983, was later listed Grade II*, and reopened as a mixed-use development in 2022.",
    source: {
      label: "Wikipedia",
      url: "https://en.wikipedia.org/wiki/Battersea_Power_Station",
    },
  },
  {
    id: "tower-bridge",
    name: "Tower Bridge",
    coordinates: [-0.0754, 51.5055],
    icon: "twin-towers",
    image: commons("Tower_Bridge_at_Dawn.jpg"),
    history:
      "Tower Bridge opened in 1894 after eight years of construction, designed by City Architect Horace Jones with engineer John Wolfe Barry. Its twin bascules still lift to let river traffic through, as they have for over a century.",
    source: {
      label: "Tower Bridge Trust",
      url: "https://www.towerbridge.org.uk/discover/history",
    },
  },
  {
    id: "st-pauls",
    name: "St Paul's Cathedral",
    coordinates: [-0.0984, 51.5138],
    icon: "dome",
    image: commons("St_Pauls_aerial_%28cropped%29.jpg"),
    history:
      "The present St Paul's is Sir Christopher Wren's masterpiece, completed in 1710 after the Great Fire of London destroyed the medieval cathedral in 1666. Its dome dominated the London skyline for two and a half centuries.",
    source: {
      label: "St Paul's Cathedral",
      url: "https://www.stpauls.co.uk/history",
    },
  },
  {
    id: "tower-of-london",
    name: "Tower of London",
    coordinates: [-0.0759, 51.5081],
    icon: "keep",
    image: commons("Tower_of_London_from_the_Shard_%288515883950%29.jpg"),
    history:
      "Founded by William the Conqueror after 1066, the Tower's White Tower was raised as a statement of Norman power over the conquered city. Across nine centuries it has served as fortress, royal palace, prison, and home of the Crown Jewels.",
    source: {
      label: "Historic Royal Palaces",
      url: "https://www.hrp.org.uk/tower-of-london/history-and-stories/",
    },
  },
  {
    id: "greenwich",
    name: "Greenwich",
    coordinates: [-0.0096, 51.4823],
    icon: "ship",
    image: commons("Northeast_View_of_the_Cutty_Sark_in_Greenwich.jpg"),
    history:
      "Maritime Greenwich pairs the Cutty Sark, the record-breaking tea clipper launched in 1869, with the Royal Observatory founded by Charles II in 1675. The Observatory has marked the Prime Meridian of the world since 1884.",
    source: {
      label: "Royal Museums Greenwich",
      url: "https://www.rmg.co.uk/",
    },
  },
  {
    id: "borough-market",
    name: "Borough Market",
    coordinates: [-0.091, 51.5054],
    icon: "market",
    image: commons("London_2018_March_IMG_0663.jpg"),
    history:
      "Borough Market traces its trading history back around 1,000 years, to a market at the southern end of London Bridge. It has stood on its present site beside Southwark Cathedral since 1756 and remains London's oldest food market.",
    source: {
      label: "Borough Market",
      url: "https://boroughmarket.org.uk/about-us/",
    },
  },
  {
    id: "monument",
    name: "The Monument",
    coordinates: [-0.0859, 51.5101],
    icon: "column",
    image: commons("The_Monument_to_the_Great_Fire_of_London.JPG"),
    history:
      "The Monument to the Great Fire of London is a 61-metre Doric column by Christopher Wren and Robert Hooke, completed in 1677. Its height equals the distance to the Pudding Lane bakery where the 1666 fire began.",
    source: {
      label: "City of London",
      url: "https://www.cityoflondon.gov.uk/things-to-do/attractions-museums-entertainment/the-monument",
    },
  },
  {
    id: "the-shard",
    name: "The Shard",
    coordinates: [-0.0865, 51.5045],
    icon: "shard",
    image: commons("The_Shard_at_sunset_2017_%28cropped%29.jpg"),
    history:
      "The Shard is western Europe's tallest building, a 310-metre spire of angled glass designed by Renzo Piano and completed in 2012. It rises straight out of London Bridge station on the site of the former Southwark Towers, its tapering facets meant to echo the masts of ships that once crowded the Thames.",
    source: {
      label: "Wikipedia",
      url: "https://en.wikipedia.org/wiki/The_Shard",
    },
  },
  {
    id: "london-eye",
    name: "London Eye",
    coordinates: [-0.1195, 51.5033],
    icon: "wheel",
    image: commons("London-Eye-2009.JPG"),
    history:
      "The London Eye is a 135-metre cantilevered observation wheel on the South Bank, opened for the millennium in 2000. Briefly the tallest of its kind in the world, its slow half-hour turn over the Thames quickly became one of the most recognisable additions to the London skyline.",
    source: {
      label: "Wikipedia",
      url: "https://en.wikipedia.org/wiki/London_Eye",
    },
  },
  {
    id: "gherkin",
    name: "30 St Mary Axe (The Gherkin)",
    coordinates: [-0.0803, 51.5145],
    icon: "gherkin",
    image: commons("30_St_Mary_Axe%2C_%27Gherkin%27.JPG"),
    history:
      "30 St Mary Axe, known to everyone as the Gherkin, is Norman Foster's 180-metre glass tower in the City, completed in 2004 on the site of the bomb-damaged Baltic Exchange. Its curved diagrid frame and rounded profile made it an instant landmark of the modern Square Mile.",
    source: {
      label: "Wikipedia",
      url: "https://en.wikipedia.org/wiki/30_St_Mary_Axe",
    },
  },
  // Second wave of iconic London landmarks — each mapped to one of the existing
  // icon keys (clock-tower, dome, twin-towers, shard, wheel, gherkin, column,
  // civic, keep, market, canal, ship, chimneys). No image field: verified photos
  // are attached separately so a guessed Wikimedia filename can't 404.
  {
    id: "buckingham-palace",
    image: commons("Buckingham_Palace_London_Morning_2020_01_%28cropped%29.jpg"),
    name: "Buckingham Palace",
    coordinates: [-0.1419, 51.5014],
    icon: "civic",
    history:
      "Buckingham Palace grew from Buckingham House, a townhouse bought by George III in 1761, and was remodelled into a palace for Queen Victoria, who made it the official royal London residence in 1837. Its familiar east front, where crowds gather at the balcony, was refaced in Portland stone in 1913.",
    source: {
      label: "Royal Collection Trust",
      url: "https://www.rct.uk/visit/buckingham-palace",
    },
  },
  {
    id: "trafalgar-square",
    image: commons("Trafalgar_Square%2C_London_2_-_Jun_2009.jpg"),
    name: "Trafalgar Square & The National Gallery",
    coordinates: [-0.1283, 51.5086],
    icon: "civic",
    history:
      "Trafalgar Square was laid out in the 1830s and 1840s to designs by Charles Barry, commemorating the 1805 naval victory at Trafalgar. Along its north side stands the National Gallery, opened in 1838, whose collection of Western European paintings dates from the 13th to the 20th centuries.",
    source: {
      label: "National Gallery",
      url: "https://www.nationalgallery.org.uk/about-us/history",
    },
  },
  {
    id: "piccadilly-circus",
    image: commons("Open_Happiness_Piccadilly_Circus_Blue-Pink_Hour_120917-1126-jikatu.jpg"),
    name: "Piccadilly Circus",
    coordinates: [-0.1348, 51.5099],
    icon: "civic",
    history:
      "Piccadilly Circus was created in 1819 where Regent Street meets Piccadilly, and became a busy West End junction as London's road network grew. Its illuminated advertising signs first appeared in the early 1900s and, with the Shaftesbury Memorial Fountain topped by the winged 'Eros', make it one of London's best-known meeting points.",
    source: {
      label: "Wikipedia",
      url: "https://en.wikipedia.org/wiki/Piccadilly_Circus",
    },
  },
  {
    id: "covent-garden",
    image: commons("Covent_Garden_Interior_May_2006_crop.jpg"),
    name: "Covent Garden",
    coordinates: [-0.1226, 51.5119],
    icon: "market",
    history:
      "Covent Garden began as a produce market on land laid out by Inigo Jones in the 1630s and grew into London's main fruit and vegetable market. The wholesale trade moved out in 1974, and the Grade II listed market halls reopened as a shopping and street-performance hub still busy today.",
    source: {
      label: "Wikipedia",
      url: "https://en.wikipedia.org/wiki/Covent_Garden",
    },
  },
  {
    id: "leadenhall-market",
    image: commons("Leadenhall_Market_In_London_-_Feb_2006_rotated.jpg"),
    name: "Leadenhall Market",
    coordinates: [-0.0836, 51.5128],
    icon: "market",
    history:
      "Leadenhall Market occupies a site that has hosted trading since Roman times, on the spot of London's ancient basilica and forum. Its ornate wrought-iron and glass roof, designed by Sir Horace Jones, dates from 1881 and covers a covered arcade of shops in the heart of the City.",
    source: {
      label: "City of London",
      url: "https://www.cityoflondon.gov.uk/things-to-do/leadenhall-market",
    },
  },
  {
    id: "somerset-house",
    image: commons("The_courtyard_of_Somerset_House%2C_Strand%2C_London_-_geograph.org.uk_-_1601172.jpg"),
    name: "Somerset House",
    coordinates: [-0.1173, 51.5111],
    icon: "civic",
    history:
      "Somerset House was built from 1776 by Sir William Chambers as a grand neoclassical block of government offices, replacing a Tudor royal palace on the Strand. Its riverside quadrangle now hosts arts and cultural events, with a fountain court that becomes an ice rink each winter.",
    source: {
      label: "Somerset House",
      url: "https://www.somersethouse.org.uk/about/our-history",
    },
  },
  {
    id: "tate-modern",
    image: commons("Tate_Modern_-_Bankside_Power_Station.jpg"),
    name: "Tate Modern",
    coordinates: [-0.0993, 51.5076],
    icon: "chimneys",
    history:
      "Tate Modern occupies the former Bankside Power Station, a brick building with a single tall chimney designed by Sir Giles Gilbert Scott and built in stages from 1947. Converted by architects Herzog & de Meuron, it opened as Britain's national gallery of modern art in 2000, with its vast Turbine Hall as the entrance.",
    source: {
      label: "Tate",
      url: "https://www.tate.org.uk/visit/tate-modern",
    },
  },
  {
    id: "the-o2",
    image: commons("O2_Arena_%289499773307%29.jpg"),
    name: "The O2 Arena",
    coordinates: [0.0031, 51.5030],
    icon: "dome",
    history:
      "The O2 is a large entertainment complex under a domed canopy on the Greenwich Peninsula, originally built as the Millennium Dome to mark the year 2000. Designed by Richard Rogers, its white tent-like roof is held up by twelve tall yellow masts and now shelters a major concert and events arena.",
    source: {
      label: "Wikipedia",
      url: "https://en.wikipedia.org/wiki/The_O2",
    },
  },
  {
    id: "hms-belfast",
    image: commons("London_November_2013-14a.jpg"),
    name: "HMS Belfast",
    coordinates: [-0.0817, 51.5065],
    icon: "ship",
    history:
      "HMS Belfast is a Royal Navy light cruiser launched in 1938 that saw service in the Second World War, including the D-Day landings, and the Korean War. Saved from scrapping, she has been moored on the Thames near Tower Bridge as a museum ship of the Imperial War Museums since 1971.",
    source: {
      label: "Imperial War Museums",
      url: "https://www.iwm.org.uk/visits/hms-belfast",
    },
  },
  {
    id: "old-royal-naval-college",
    image: commons("Royal_Naval_College_Greenwich_view_from_the_Thames.jpg"),
    name: "Old Royal Naval College, Greenwich",
    coordinates: [-0.0053, 51.4834],
    icon: "dome",
    history:
      "The Old Royal Naval College is Sir Christopher Wren's baroque riverside masterpiece at Greenwich, begun in 1696 as a hospital for retired sailors on the site of a former royal palace. Its twin domed halls frame a view to the Queen's House, and the Painted Hall is celebrated for James Thornhill's ceiling.",
    source: {
      label: "Old Royal Naval College",
      url: "https://ornc.org/about-us/history/",
    },
  },
  {
    id: "kensington-palace",
    image: commons("Kensington_Palace%2C_the_South_Front_-_geograph.org.uk_-_287402.jpg"),
    name: "Kensington Palace",
    coordinates: [-0.1877, 51.5050],
    icon: "civic",
    history:
      "Kensington Palace became a royal residence in 1689 when William III and Mary II bought Nottingham House and had Sir Christopher Wren enlarge it. It was the birthplace and childhood home of Queen Victoria and remains a working royal palace set within Kensington Gardens.",
    source: {
      label: "Historic Royal Palaces",
      url: "https://www.hrp.org.uk/kensington-palace/history-and-stories/",
    },
  },
  {
    id: "marble-arch",
    image: commons("Marble_Arch_%2829797251968%29.jpg"),
    name: "Marble Arch",
    coordinates: [-0.1590, 51.5131],
    icon: "civic",
    history:
      "Marble Arch is a white Carrara-marble triumphal arch designed by John Nash in 1827, first built as a gateway to Buckingham Palace. It was moved to its present site at the north-east corner of Hyde Park in 1851, near the historic site of the Tyburn gallows.",
    source: {
      label: "Wikipedia",
      url: "https://en.wikipedia.org/wiki/Marble_Arch",
    },
  },
  {
    id: "hampton-court-palace",
    image: commons("Hampton_Court_Palace%2C_West_Front_Richmond_upon_Thames_1193127_20230823_0050.jpg"),
    name: "Hampton Court Palace",
    coordinates: [-0.3376, 51.4036],
    icon: "keep",
    history:
      "Hampton Court Palace was built by Cardinal Wolsey from 1515 and taken over by Henry VIII, who made it one of the most lavish Tudor palaces in England. A later baroque range added for William III and Mary II gives the palace its dual character of red-brick Tudor and English baroque, set in famous riverside gardens with a maze.",
    source: {
      label: "Historic Royal Palaces",
      url: "https://www.hrp.org.uk/hampton-court-palace/history-and-stories/",
    },
  },
  {
    id: "little-venice",
    image: commons("Little_Venice_in_March.jpg"),
    name: "Little Venice",
    coordinates: [-0.1830, 51.5220],
    icon: "canal",
    history:
      "Little Venice is a tranquil basin in Maida Vale where the Regent's Canal meets the Grand Union Canal, lined with moored narrowboats and waterside cafes. The canals were dug in the early 19th century for freight, and the leafy pool is now a quiet corner of London named for its resemblance to the Italian city.",
    source: {
      label: "Wikipedia",
      url: "https://en.wikipedia.org/wiki/Little_Venice,_London",
    },
  },
  {
    id: "alexandra-palace",
    image: commons("APalace_1.jpg"),
    name: "Alexandra Palace",
    coordinates: [-0.1310, 51.5943],
    icon: "civic",
    history:
      "Alexandra Palace opened in 1873 as a public entertainment hall on a hilltop in north London, and was quickly rebuilt after fire destroyed it within weeks. From its mast the BBC broadcast the world's first regular high-definition television service in 1936, earning it the nickname 'the birthplace of television'.",
    source: {
      label: "Alexandra Palace",
      url: "https://www.alexandrapalace.com/our-story/",
    },
  },
];

/** Look up one curated landmark by id (shareable chapter pages, deep links). */
export function landmarkById(id: string | null | undefined): Landmark | undefined {
  if (!id) return undefined;
  return landmarks.find((landmark) => landmark.id === id);
}

// Inverse of nearestStoryPubs: given a point (usually a venue), list the
// nearest curated landmarks within `maxKm`. Used by the Lore "Around here"
// place-stories section — names only, no history dump.
export type NearbyLandmark = { landmark: Landmark; km: number };

export function nearestLandmarks(
  coordinates: [number, number],
  limit = 3,
  maxKm = 0.75,
  catalog: readonly Landmark[] = landmarks,
): NearbyLandmark[] {
  return catalog
    .map((landmark) => ({
      landmark,
      km: haversineKm(landmark.coordinates, coordinates),
    }))
    .filter((row) => row.km <= maxKm)
    .sort((a, b) => a.km - b.km)
    .slice(0, limit);
}
