/**
 * Direct client fetches that are not reusable painted reads.
 *
 * This is a shrinking declaration. A component read belongs in
 * surfaceDataCache.ts whenever it paints a reloadable surface. Entries here
 * cover mutations, auth and identity, Social no-store lanes, map interaction
 * reads, and other flows with their own lifecycle or privacy contract.
 */
export type SurfaceReadExemption = {
  path: string;
  fetchCount: number;
  reason: string;
};

export const SURFACE_READ_EXEMPTIONS = [
  { path: "app/admin/AdminClient.tsx", fetchCount: 29, reason: "admin moderation reads and writes use the admin lane" },
  { path: "app/discover/DiscoverPageClient.tsx", fetchCount: 2, reason: "Social discover access and feed reads are explicit no-store" },
  { path: "app/feed/FeedPageClient.tsx", fetchCount: 6, reason: "Social feed and optimistic post actions keep their no-store and retry semantics" },
  { path: "app/rounds/[code]/RoundPageClient.tsx", fetchCount: 2, reason: "shared round view and report actions use their own lifecycle" },
  { path: "app/social/SocialComposer.tsx", fetchCount: 1, reason: "Social composer venue search is no-store; mutations use the shared auth transport" },
  { path: "app/social/crews/[crewId]/CrewDetailClient.tsx", fetchCount: 3, reason: "Social crew access and actions are no-store by policy" },
  { path: "app/u/[handle]/ProfilePageClient.tsx", fetchCount: 1, reason: "handle alias resolution is an identity read and must never be cached" },
  { path: "components/LandlordPanel.tsx", fetchCount: 1, reason: "heritage question is a user-submitted request, not a painted reload surface" },
  { path: "components/PubMap.tsx", fetchCount: 3, reason: "map data packs and viewport streams have map-owned cache policy" },
  { path: "components/PubMapCanvas.tsx", fetchCount: 2, reason: "venue selection and route interaction are map-owned reads" },
  { path: "components/areanews/AreaNewsBlock.tsx", fetchCount: 1, reason: "venue news is an additive detail read with its own freshness lane" },
  { path: "components/areanews/VenueAwardBadge.tsx", fetchCount: 1, reason: "venue award detail is an additive map read" },
  { path: "components/auth/HandlePasswordSignIn.tsx", fetchCount: 1, reason: "password sign-in is auth and explicitly denied" },
  { path: "components/city/CityChooser.tsx", fetchCount: 1, reason: "city pack loading is owned by the chooser and map data lifecycle" },
  { path: "components/coverage/UnsupportedAreaPreview.tsx", fetchCount: 1, reason: "coverage preview is an optional area-demand probe" },
  { path: "components/desktop/AreaNewsRail.tsx", fetchCount: 1, reason: "area news rail has a separate additive freshness contract" },
  { path: "components/feed/PresenceStrip.tsx", fetchCount: 1, reason: "Social presence is live and no-store" },
  { path: "components/landing/PintDropStrip.tsx", fetchCount: 1, reason: "landing contribution strip has anonymous demo fallback semantics" },
  { path: "components/map/ActiveRoundChip.tsx", fetchCount: 1, reason: "active round is a live plan interaction" },
  { path: "components/map/CityPlaceStrip.tsx", fetchCount: 2, reason: "map place search and enrichment are interactive map reads" },
  { path: "components/map/CityStatusBanner.tsx", fetchCount: 1, reason: "map status is an optional provider status lane" },
  { path: "components/map/CitySuggestBanner.tsx", fetchCount: 1, reason: "map search suggestion is an interactive pack read" },
  { path: "components/map/NearbyBusDepartures.tsx", fetchCount: 1, reason: "nearby transport is live and location-scoped" },
  { path: "components/map/UnverifiedPubSheet.tsx", fetchCount: 1, reason: "harvest overlay is an additive lazy read for one unverified pub sheet and never paints a reload surface" },
  { path: "components/map/VenueBuzz.tsx", fetchCount: 2, reason: "venue search and buzz are interactive detail reads" },
  { path: "components/map/VenueHygiene.tsx", fetchCount: 1, reason: "venue hygiene lookup is an additive detail read" },
  { path: "components/map/VenuePriceStory.tsx", fetchCount: 2, reason: "price story reads and confirmation action use the price lane" },
  { path: "components/map/VenueWeatherRecommendations.tsx", fetchCount: 1, reason: "venue weather recommendations are location and venue interaction reads" },
  { path: "components/map/pubmap/useActivePlanRoute.ts", fetchCount: 1, reason: "active plan state is no-store and mutation-sensitive" },
  { path: "components/map/pubmap/useUkBaseStreaming.ts", fetchCount: 1, reason: "UK base shard streaming is viewport-owned data loading" },
  { path: "components/map/useCommunityPrices.ts", fetchCount: 5, reason: "community price reads and writes have distinct authority and provisional-mark policy" },
  { path: "components/map/useCrawlJourneys.ts", fetchCount: 1, reason: "crawl journey reads are live route interaction" },
  { path: "components/map/usePintDrops.ts", fetchCount: 3, reason: "map Pint Drop reads and writes use the map feed lane" },
  { path: "components/map/useVenueJourney.ts", fetchCount: 1, reason: "venue journey is location and route interaction" },
  { path: "components/map/useVenueOccupancy.ts", fetchCount: 2, reason: "occupancy now-read is fail-soft and must never cache as an empty pub; flag fallback uses bare fetch when auth is absent, and the report beside it is a write" },
  { path: "components/out/useOutListings.ts", fetchCount: 1, reason: "an answer is held with the day it is about, so a pressed day chip repaints pending rather than another day's cached answer" },
  { path: "components/messages/MessageVenuePicker.tsx", fetchCount: 1, reason: "message composer typeahead must not cache partial queries" },
  { path: "components/night/NightCalmLine.tsx", fetchCount: 1, reason: "night calm is an optional live signal" },
  { path: "components/night/NightModeCard.tsx", fetchCount: 7, reason: "night plan state, venue data, and actions are no-store interactive flows" },
  { path: "components/pintdrop/CommentThread.tsx", fetchCount: 1, reason: "comments are Social interaction reads and mutations" },
  { path: "components/plan/LastCrewInvite.tsx", fetchCount: 1, reason: "invite state is mutation-sensitive plan context" },
  { path: "components/plan/MatchGroupPrefs.tsx", fetchCount: 3, reason: "shared plan collaboration state is no-store" },
  { path: "components/plan/MobilePlanActivation.tsx", fetchCount: 2, reason: "plan activation is a user action and generation request" },
  { path: "components/plan/NightCrawlMode.tsx", fetchCount: 1, reason: "plan mode state is no-store and mutation-sensitive" },
  { path: "components/plan/PlanCollaborationPanel.tsx", fetchCount: 7, reason: "plan collaboration reads and actions are no-store" },
  { path: "components/plan/PlanComposer.tsx", fetchCount: 4, reason: "plan creation and metadata are interactive mutations" },
  { path: "components/plan/PlanCrew.tsx", fetchCount: 4, reason: "plan crew reads and actions are no-store" },
  { path: "components/plan/PlanHostInviteLink.tsx", fetchCount: 2, reason: "invite link reads and rotation are mutation-sensitive" },
  { path: "components/plan/PlanInviteNextStep.tsx", fetchCount: 1, reason: "invite next-step state is no-store" },
  { path: "components/plan/PlanInviteRsvp.tsx", fetchCount: 3, reason: "invite RSVP reads and actions are mutation-sensitive" },
  { path: "components/plan/PlanRoute.tsx", fetchCount: 2, reason: "plan route and Tonight listings have no-store route semantics" },
  { path: "components/plan/PlanRouteMiniMap.tsx", fetchCount: 2, reason: "plan map detail is interactive venue data" },
  { path: "components/plan/PlanSummary.tsx", fetchCount: 3, reason: "plan summary reads and actions are no-store" },
  { path: "components/plan/PlanVibe.tsx", fetchCount: 3, reason: "plan votes are live and mutation-sensitive" },
  { path: "components/plan/RecapDetail.tsx", fetchCount: 1, reason: "recap detail is a private mutable surface" },
  { path: "components/profile/OutTonightBoard.tsx", fetchCount: 1, reason: "presence is live and account-scoped" },
  { path: "components/pubpal/PubPalVoice.tsx", fetchCount: 1, reason: "voice availability is a per-deployment configuration probe, not a painted surface read" },
  { path: "components/profile/OutTonightCrewLine.tsx", fetchCount: 1, reason: "presence is live and account-scoped" },
  { path: "components/profile/OutTonightToggle.tsx", fetchCount: 1, reason: "presence read and toggle are live account actions" },
  { path: "components/profile/SavedListDetail.tsx", fetchCount: 1, reason: "saved-list detail is private viewer context with mutation-sensitive state" },
  { path: "components/ratings/ratingsClient.ts", fetchCount: 1, reason: "rating client is an additive detail read" },
  { path: "components/savedpubs/SaveToListControl.tsx", fetchCount: 1, reason: "saved-pub action is a mutation" },
  { path: "components/social/CreatorListsLane.tsx", fetchCount: 1, reason: "Social creator-list discovery is no-store" },
  { path: "components/social/FindYourLot.tsx", fetchCount: 1, reason: "Social discovery is no-store" },
  { path: "components/social/PeopleDirectory.tsx", fetchCount: 4, reason: "Social directory and follow actions are no-store" },
  { path: "components/social/PublicCrewRouteClient.tsx", fetchCount: 1, reason: "public Open Crew preview is a no-store route with identity-scoped lifecycle guards" },
  { path: "components/visits/visitReportsClient.ts", fetchCount: 2, reason: "Visit Report reader and flag action have their own freshness and moderation lane" },
  { path: "components/map/inspector/VenueStoryTab.tsx", fetchCount: 1, reason: "venue story is an additive map detail read" },
  { path: "lib/analytics.ts", fetchCount: 2, reason: "analytics transport is fire-and-forget telemetry, never painted data" },
  { path: "lib/adminSessionClient.ts", fetchCount: 1, reason: "admin session transport must confirm the browser kept the secure session cookie" },
  { path: "lib/authedFetch.ts", fetchCount: 3, reason: "shared graceful and strict bearer transports serve auth-gated actions and public reads" },
  { path: "lib/savedPubs.ts", fetchCount: 2, reason: "saved-list reads are private viewer context with their own mutation-sensitive state" },
  { path: "lib/heritage.ts", fetchCount: 1, reason: "heritage question is a user-submitted request, not a painted reload surface" },
  { path: "lib/pois.ts", fetchCount: 1, reason: "map POI pack is static viewport data with map-owned lifecycle" },
  { path: "lib/tflDisruption.ts", fetchCount: 1, reason: "transport provider client has its own live disruption contract" },
  { path: "lib/slimShards.ts", fetchCount: 3, reason: "static map shard loading is owned by the map data lifecycle" },
  { path: "lib/venuesSlim.ts", fetchCount: 2, reason: "static venue pack loading is owned by the map data lifecycle" },
  { path: "lib/optimisticSpillPost.ts", fetchCount: 1, reason: "feed overflow transport is an optimistic mutation fallback" },
  { path: "lib/reactionClient.ts", fetchCount: 1, reason: "Social reaction reads and writes are no-store interaction state" },
  { path: "lib/prefetchVenue.ts", fetchCount: 1, reason: "hover prefetch warms an interaction detail, not a painted reload read" },
  { path: "lib/ukBasePubs.ts", fetchCount: 2, reason: "UK base shard loading is viewport-owned static map data" },
  { path: "lib/webPush.ts", fetchCount: 2, reason: "push subscription transport is an account action" },
  { path: "lib/planSessionCapability.ts", fetchCount: 1, reason: "plan capability exchange is an auth-gated session read" },
  { path: "lib/planMutationOutbox.ts", fetchCount: 1, reason: "offline plan outbox replays mutations" },
  { path: "lib/mapWarmup.ts", fetchCount: 2, reason: "map warmup prefetch is owned by map startup and never paints directly" },
  { path: "lib/planRouteTotalsClient.ts", fetchCount: 1, reason: "plan route totals are interactive route state" },
  { path: "lib/nativePush.ts", fetchCount: 1, reason: "native push subscription transport is an account action" },
  { path: "lib/nativeCamera.ts", fetchCount: 1, reason: "native camera bridge reads a local photo blob, not app data" },
  { path: "lib/lastRideClient.ts", fetchCount: 1, reason: "last-ride lookup is an optional transport interaction" },
  { path: "lib/publicJsonLoader.ts", fetchCount: 1, reason: "shared fetch behind the price history, price update and Pint Index league loaders, each an additive map detail/static lane, never a painted reload read" },
  { path: "lib/wetherspoonsDirectory.ts", fetchCount: 1, reason: "directory data is static optional map content" },
  { path: "lib/nearDeskVenues.ts", fetchCount: 1, reason: "desk pack loading is owned by the Desk mode data lifecycle" },
  { path: "lib/deviceAccountSwitch.ts", fetchCount: 1, reason: "account switching is auth transport and identity must never be cached" },
  { path: "lib/warmVenueDetail.ts", fetchCount: 1, reason: "venue detail prefetch warms interaction state" },
] as const satisfies readonly SurfaceReadExemption[];
