#!/usr/bin/env node
// Borough coverage report (Cycle 3 — Lane 2 "every single area in London").
//
// Measures, for each of the 33 Greater London boroughs, how many venues are in
// the complete slim index behind the map's spatial shards and how many carry a
// usable price the persona can act on. The map groups pins by the slim
// `borough` field, so that is the number the persona in Croydon or Barnet
// experiences when its cells load. The report counts exactly that, then
// cross-checks every venue's stored borough against the point-in-polygon
// classifier so a mislabelled pin cannot inflate a borough's number.
//
// Provenance note: the bundled price dataset (public/data/pint_prices_app_dataset.json)
// carries NO per-row observation date, so a per-borough "freshest observation"
// cannot be derived from it. The dataset's provenance date is the scheduled
// price-refresh snapshot under public/data/price_updates/ (reported once, global).
//
// Run: node scripts/report_borough_coverage.mjs
//   Writes docs/BOROUGH_COVERAGE_<YYYY-MM-DD>.md (markdown table).
//   Prints the same table to stdout. Read-only over the data; writes docs only.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { boroughForPoint, LONDON_BOROUGH_CLASSIFIER_VERSION } from "./lib/boroughFromPoint.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SLIM_PATH = join(ROOT, "public", "data", "venues_slim.json");
const PRICE_UPDATES_DIR = join(ROOT, "public", "data", "price_updates");

// The 33 real Greater London boroughs (mirrors lib/boroughs.ts LONDON_BOROUGHS,
// which __tests__/boroughs.test.ts asserts equals the classifier GeoJSON).
const LONDON_BOROUGHS = [
  "Barking and Dagenham", "Barnet", "Bexley", "Brent", "Bromley", "Camden",
  "City of London", "Croydon", "Ealing", "Enfield", "Greenwich", "Hackney",
  "Hammersmith and Fulham", "Haringey", "Harrow", "Havering", "Hillingdon",
  "Hounslow", "Islington", "Kensington and Chelsea", "Kingston upon Thames",
  "Lambeth", "Lewisham", "Merton", "Newham", "Redbridge", "Richmond upon Thames",
  "Southwark", "Sutton", "Tower Hamlets", "Waltham Forest", "Wandsworth",
  "Westminster",
];

function hasUsablePrice(v) {
  return typeof v.cheapestPrice === "number" && Number.isFinite(v.cheapestPrice);
}

function latestPriceSnapshotDate() {
  try {
    const files = readdirSync(PRICE_UPDATES_DIR).filter((f) => /^prices_\d{8}\.json$/.test(f));
    files.sort();
    const last = files[files.length - 1];
    if (!last) return null;
    const m = last.match(/^prices_(\d{4})(\d{2})(\d{2})\.json$/);
    return m ? `${m[1]}-${m[2]}-${m[3]}` : null;
  } catch {
    return null;
  }
}

function main() {
  const payload = JSON.parse(readFileSync(SLIM_PATH, "utf8"));
  const slim = Array.isArray(payload)
    ? payload
    : Array.isArray(payload?.rows)
      ? payload.rows
      : [];

  const stat = new Map();
  for (const b of LONDON_BOROUGHS) stat.set(b, { total: 0, priced: 0, geoMismatch: 0 });
  const unmatched = { total: 0, priced: 0 };

  for (const v of slim) {
    const borough = v.borough || "";
    const bucket = stat.get(borough);
    if (!bucket) {
      unmatched.total += 1;
      if (hasUsablePrice(v)) unmatched.priced += 1;
      continue;
    }
    bucket.total += 1;
    if (hasUsablePrice(v)) bucket.priced += 1;
    const geo = boroughForPoint(v.lat, v.lng);
    if (geo && geo !== borough) bucket.geoMismatch += 1;
  }

  const rows = LONDON_BOROUGHS.map((b) => {
    const s = stat.get(b);
    return { borough: b, ...s, ratio: s.total ? s.priced / s.total : 0 };
  });
  rows.sort((a, z) => a.priced - z.priced || a.total - z.total || a.borough.localeCompare(z.borough));

  const totalVenues = rows.reduce((a, r) => a + r.total, 0);
  const totalPriced = rows.reduce((a, r) => a + r.priced, 0);
  const snapshot = latestPriceSnapshotDate();
  const today = new Date().toISOString().slice(0, 10);

  const pct = (n) => `${(n * 100).toFixed(0)}%`;
  const lines = [];
  lines.push(`# Borough coverage — ${today}`);
  lines.push("");
  lines.push(`Generated by \`scripts/report_borough_coverage.mjs\` over \`public/data/venues_slim.json\` (the slim index the live map reads). Classifier version \`${LONDON_BOROUGH_CLASSIFIER_VERSION}\`.`);
  lines.push("");
  lines.push(`- **Venues on the map:** ${totalVenues} across 33 boroughs (+${unmatched.total} unmatched/out-of-borough).`);
  lines.push(`- **Priced venues:** ${totalPriced} (${pct(totalVenues ? totalPriced / totalVenues : 0)}) carry a usable cheapest-pint price; the rest render as unpriced pins.`);
  lines.push(`- **Price-snapshot provenance:** ${snapshot ? `latest scheduled refresh snapshot \`prices_${snapshot.replace(/-/g, "")}.json\` (${snapshot})` : "no scheduled price snapshot on disk"}. The bundled dataset carries no per-row observation date, so no per-borough freshness column is derivable — see the note below.`);
  lines.push("");
  lines.push("`geo≠stored` = venues whose stored borough differs from the point-in-polygon classifier for their own lat/lng (data-quality signal; the map groups by the stored value).");
  lines.push("");
  lines.push("| Borough | Venues | Priced | Coverage | Unpriced | geo≠stored |");
  lines.push("|---|---:|---:|---:|---:|---:|");
  for (const r of rows) {
    lines.push(`| ${r.borough} | ${r.total} | ${r.priced} | ${pct(r.ratio)} | ${r.total - r.priced} | ${r.geoMismatch} |`);
  }
  lines.push(`| **Total** | **${totalVenues}** | **${totalPriced}** | **${pct(totalVenues ? totalPriced / totalVenues : 0)}** | **${totalVenues - totalPriced}** | — |`);
  lines.push("");
  lines.push("### Freshness caveat");
  lines.push("");
  lines.push("`public/data/pint_prices_app_dataset.json` rows have no `observedAt`/date field, so a per-venue or per-borough \"freshest observation date\" cannot be computed from the shipped data. Dated provenance exists only at the snapshot level in `public/data/price_updates/prices_YYYYMMDD.json` (and the drink/food equivalents). Any future per-observation freshness needs a dated field carried through the export pipeline.");
  lines.push("");
  lines.push("### Worst 10 boroughs by priced-venue count (persona-hollow first)");
  lines.push("");
  lines.push("These are the areas where the 9-to-5 persona is most likely to open the map to little or nothing. All are Outer London.");
  lines.push("");
  lines.push("| Rank | Borough | Priced venues | Total venues | Coverage |");
  lines.push("|---:|---|---:|---:|---:|");
  rows.slice(0, 10).forEach((r, i) => {
    lines.push(`| ${i + 1} | ${r.borough} | ${r.priced} | ${r.total} | ${pct(r.ratio)} |`);
  });
  lines.push("");
  lines.push("## Ingestion pipeline (read before expanding)");
  lines.push("");
  lines.push("The London slim index the map reads is built by a deterministic, no-network chain over one committed source of truth — `public/data/pint_prices_app_dataset.json`:");
  lines.push("");
  lines.push("```");
  lines.push("export:data (python, from data/*.csv)  ->  canonicalize:venues  ->  build:slim  ->  build:pubmaxxing-seed");
  lines.push("```");
  lines.push("");
  lines.push("- **`export:data`** (`scripts/export_app_dataset_json.py`) rebuilds the app dataset from the committed CSV lineages under `data/` and assigns `primary_borough` via the same point-in-polygon classifier as `lib/londonBoroughPoint.mjs`. No keys, no network.");
  lines.push("- **`canonicalize:venues`** (`scripts/canonicalize_venue_dataset.mjs`) collapses duplicate physical pubs across lineages in place and writes `venue_id_aliases.json`. Idempotent, no network.");
  lines.push("- **`build:slim`** (`scripts/build_slim_index.mjs`) groups rows by the FNV-1a stable venue id (mirrors `lib/venues.ts`), keeps the min numeric `price_gbp` as `cheapestPrice`, and stamps `borough` from `primary_borough`. **Coverage in this report is measured off this artifact.** No keys, no network. Confirmed reproducible: a full rebuild produced a byte-identical `venues_slim.json` (zero git diff).");
  lines.push("- **Venue presence (unpriced pins)** enters only through curated, provenance-stamped gazetteer seeds merged by `scripts/merge_outer_london_gazetteer.mjs` (`data/outer_london_gazetteer_seed.json`, 66 Outer London pubs across Havering/Hillingdon/Redbridge/Barnet/Harrow) and `scripts/merge_london_chain_gazetteer.mjs` (`data/london_chain_gazetteer_seed.json`, 63 chain pubs). Every seed row carries `provenance: \"sourced\"` + a `source_note`; nothing is invented.");
  lines.push("");
  lines.push("### Price-refresh sources & provenance rules");
  lines.push("");
  lines.push("- **`refresh:prices`** (`scripts/refresh_prices.mjs`) reads the `data/price_sources.json` allowlist and refuses any URL not marked `first-party-official` / `open-data`. Its `fetchFromSource()` is a documented **stub returning `[]`** and the allowlist holds only `example-*` placeholders — so a run is a safe no-op that adds no rows.");
  lines.push("- **`refresh:drink-prices`** (`scripts/refresh_drink_prices.mjs`) + the Firecrawl chain harvesters (`firecrawl_greene_king_prices.mjs`, `firecrawl_mbplc_prices.mjs`) target first-party chain drink menus (Greene King, Nicholson's, Wetherspoons). These require `FIRECRAWL_API_KEY` and live network access. **They feed `public/data/drink_price_updates/` — a separate runtime overlay read at venue-detail time — NOT the slim index's `cheapestPrice`.** `build_slim_index.mjs` reads no `price_updates` file, so running them does not change any number in this coverage table.");
  lines.push("- **Hard governance (all refreshers):** every emitted price carries `{ source, observedAt }` (or `licence`), rows that can't be attributed to a specific venue are dropped (never guessed), no competitor price-aggregators, and output goes through a reviewed PR — never a push to main.");
  lines.push("");
  lines.push("## Expansion status (this cycle)");
  lines.push("");
  lines.push("Honest accounting of what could be run to raise coverage using the EXISTING scripts:");
  lines.push("");
  lines.push("- **Gazetteer seeds — exhausted.** Both merges are already fully applied (`merge_london_chain_gazetteer` → 0 merged / 63 skipped). Re-running `merge_outer_london_gazetteer` merges 1 \"new\" row — but it is a **coordinate-drift duplicate** of *The Moon on the Hill – JD Wetherspoon* (Harrow), which already exists with canonical priced rows: the seed's coords (51.5795, -0.335) round differently from the already-merged copy (51.5794, -0.3342), dodging the 4-decimal dedup key. This was **not committed** (it would double a pin). Filed as a seed/dedup finding for a later cycle.");
  lines.push("- **`refresh:prices` — nothing to run.** Stub + placeholder allowlist; produces no rows.");
  lines.push("- **Firecrawl drink harvesters — out of scope for this metric.** `FIRECRAWL_API_KEY` is available, but the output is a drink-menu overlay that does not touch slim `cheapestPrice`/borough coverage, so running it cannot improve this table. Left for the drinks-enrichment lane, not the coverage lane.");
  lines.push("- **No keyless London venue-ingestion path exists.** `fetch:city-pubs` (Overpass/OSM, keyless) is scoped to the non-London Wave-2 cities (Manchester, Liverpool, …), not Greater London. Adding Outer-London pub *presence* at scale would need a new curated seed or a new ingestion script — deliberately out of scope for \"expand via existing scripts\".");
  lines.push("");
  lines.push("**Net:** the deliverable this cycle is the honest coverage table above; no data rows were added (every honest lever is either exhausted, stubbed, or off-metric). The clearest next-cycle wins are Outer-London **venue presence** in the worst-10 boroughs (curated sourced seed rows, unpriced pins acceptable) and adding a dated `observedAt` to the export so freshness becomes measurable.");

  const outText = lines.join("\n") + "\n";
  const outPath = join(ROOT, "docs", `BOROUGH_COVERAGE_${today}.md`);
  writeFileSync(outPath, outText);

  // Console echo (worst-first).
  console.log(outText);
  console.log(`wrote ${outPath}`);
}

main();
